# Email Integration Example
# This configuration sends alerts via email using a webhook-to-email service

server:
  port: 8080

destinations:
  # SendGrid Email API
  - name: "email-sendgrid"
    url: "https://api.sendgrid.com/v3/mail/send"
    method: "POST"
    format: "json"
    engine: "jq"
    transform: |
      {
        personalizations: [{
          to: [
            { email: "${env:ONCALL_EMAIL}" },
            { email: "${env:TEAM_EMAIL}" }
          ],
          subject: (
            (if .status == "firing" then "[ALERT] " else "[RESOLVED] " end) +
            .groupLabels.alertname + " - " +
            (.commonLabels.severity // "unknown") + " - " +
            (.commonLabels.env // "production")
          )
        }],
        from: {
          email: "alerts@example.com",
          name: "Prometheus Alertmanager"
        },
        content: [{
          type: "text/html",
          value: (
            "<h2>" + (if .status == "firing" then "Alert Firing" else "Alert Resolved" end) + "</h2>" +
            "<p><strong>" + .groupLabels.alertname + "</strong> - " + (.commonLabels.severity // "unknown") + "</p>" +
            "<p>" + (.commonAnnotations.summary // "No summary available") + "</p>" +
            "<p>Alert Count: " + (.alerts | length | tostring) + "</p>" +
            "<p><a href='" + .externalURL + "'>View in Alertmanager</a></p>"
          )
        }],
        mail_settings: {
          sandbox_mode: {
            enable: false
          }
        },
        tracking_settings: {
          click_tracking: {
            enable: false
          },
          open_tracking: {
            enable: false
          }
        }
      }
    headers:
      Authorization: "Bearer ${env:SENDGRID_API_KEY}"
      Content-Type: "application/json"
    enabled: true
    retry:
      max_attempts: 3
      backoff: exponential
      initial_delay: 2s
      max_delay: 30s

