# Multi-Destination Routing Example
# This configuration demonstrates routing alerts to different destinations based on severity

server:
  port: 8080

destinations:
  # Critical alerts go to PagerDuty for immediate attention
  - name: "critical-pagerduty"
    url: "https://events.pagerduty.com/v2/enqueue"
    method: "POST"
    format: "json"
    engine: "jq"
    transform: |
      if .commonLabels.severity == "critical" then
        {
          routing_key: "${env:PAGERDUTY_CRITICAL_KEY}",
          event_action: (if .status == "firing" then "trigger" else "resolve" end),
          dedup_key: .groupKey,
          payload: {
            summary: "CRITICAL: " + .groupLabels.alertname,
            severity: "critical",
            source: .externalURL
          }
        }
      else empty end
    headers:
      Content-Type: "application/json"
    enabled: true
