# Splunk HTTP Event Collector (HEC) Integration Example
# This configuration sends alerts to Splunk for indexing and analysis

server:
  port: 8080

destinations:
  - name: "splunk-hec"
    url: "${env:SPLUNK_HEC_URL}/services/collector/event"
    method: "POST"
    format: "json"
    engine: "jq"
    transform: |
      {
        time: now,
        source: "prometheus-alertmanager",
        sourcetype: "_json",
        index: ("${env:SPLUNK_INDEX}" // "alerts"),
        host: .externalURL | split("//")[1] | split("/")[0],
        event: {
          alert_name: .groupLabels.alertname,
          status: .status,
          severity: (.commonLabels.severity // "info"),
          alert_count: (.alerts | length),
          group_key: .groupKey,
          summary: .commonAnnotations.summary
        }
      }
    headers:
      Authorization: "Splunk ${env:SPLUNK_HEC_TOKEN}"
      X-Splunk-Request-Channel: "${env:SPLUNK_CHANNEL_ID}"
    enabled: true

