# Microsoft Teams Integration Example
# This configuration sends alerts to Microsoft Teams using incoming webhooks

server:
  port: 8080

destinations:
  - name: "teams"
    url: "${env:TEAMS_WEBHOOK_URL}"
    method: "POST"
    format: "json"
    engine: "go-template"
    template: |
      {
        "@type": "MessageCard",
        "@context": "https://schema.org/extensions",
        "themeColor": "{{if eq .Status "firing"}}{{if eq (index .CommonLabels "severity") "critical"}}D73A49{{else if eq (index .CommonLabels "severity") "warning"}}FFA500{{else}}439FE0{{end}}{{else}}28A745{{end}}",
        "summary": "{{.GroupLabels.alertname}} is {{.Status}}",
        "sections": [
          {
            "activityTitle": "🚨 {{.GroupLabels.alertname}}",
            "activitySubtitle": "Status: {{.Status | title}} | Alerts: {{len .Alerts}}",
            "activityImage": "https://prometheus.io/assets/prometheus_logo_grey.svg",
            "facts": [
              {
                "name": "Alert Name:",
                "value": "{{.GroupLabels.alertname}}"
              },
              {
                "name": "Severity:",
                "value": "{{index .CommonLabels "severity" | default "unknown" | title}}"
              },
              {
                "name": "Environment:",
                "value": "{{index .CommonLabels "env" | default "production"}}"
              },
              {
                "name": "Alert Count:",
                "value": "{{len .Alerts}}"
              }
            ],
            "markdown": true
          },
          {
            "activityTitle": "Summary",
            "text": "{{.CommonAnnotations.summary | default "No summary available"}}"
          },
          {{if .CommonAnnotations.description}}
          {
            "activityTitle": "Description",
            "text": "{{.CommonAnnotations.description}}"
          },
          {{end}}
          {
            "activityTitle": "Affected Instances",
            "facts": [
              {{range $i, $alert := .Alerts}}
              {{if $i}},{{end}}
              {
                "name": "{{$alert.Labels.instance | default "unknown"}}",
                "value": "{{$alert.Status}} since {{$alert.StartsAt | timeformat "15:04:05"}}"
              }
              {{end}}
            ]
          }
        ],
        "potentialAction": [
          {
            "@type": "OpenUri",
            "name": "View in Alertmanager",
            "targets": [
              {
                "os": "default",
                "uri": "{{.ExternalURL}}"
              }
            ]
          }
          {{if .CommonAnnotations.runbook_url}},
          {
            "@type": "OpenUri",
            "name": "📚 Runbook",
            "targets": [
              {
                "os": "default",
                "uri": "{{.CommonAnnotations.runbook_url}}"
              }
            ]
          }
          {{end}}
          {{if .CommonAnnotations.dashboard_url}},
          {
            "@type": "OpenUri",
            "name": "📊 Dashboard",
            "targets": [
              {
                "os": "default",
                "uri": "{{.CommonAnnotations.dashboard_url}}"
              }
            ]
          }
          {{end}}
        ]
      }
    enabled: true
