name: tests-golang

on:
  push:
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.25

      - name: Test
        run: go test -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Publish coverage
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: ./coverage.txt

  race:
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.25

      - name: Test Race
        run: go test -race -v ./...
